---
- name: Provision image
  hosts: default
  become: true
  
  tasks:
    - name: Install Java
      ansible.builtin.apt:
        pkg:
          - openjdk-8-jdk
          - openjdk-21-jdk
          - tomcat9
        update_cache: yes
